Embedded Software: TCProcessor Class Reference
TCProcessor Class Reference
#include <TCProcessor.h>
Public Types
enum TC_ACTION { EXECUTE, ENABLE, DISABLE }
enum ERROR_STATE { NO_ERROR, INVALID_OPCODE, INVALID_ACTION }
Public Member Functions
TCProcessor ()
The constructor only initializes private attributes of this class.
void init ()
The init function will call 'init' on all the telecommands of this class. This function must be called from the setup function in the main.
void processRecv (String payload)
This function processes the input string which contains the OPCODE to concerned along with the action to take. This function will set the internal error variable accordingly, if there is an error of course. This function calls the process function which manages command execution, enabling, disabling, etc.
void perform (TC_ACTION action, int opcode)
This function will perform the given action on the given opcode. The internal error variable will reflect whether the OPCODE is valid. Due to the limiting actions exposed by TC_ACTION, there is no need to check for the validity of the action.
virtual ~TCProcessor ()
Private Member Functions
void define_ ()
The define_ function will define all the TCs available. It is called from the constructor and it populates the map. This is where the correspondence between the OPCODE and the given TC is done. Note that this also where the Start of Service tool output should be place (for TC generation).
Private Attributes
std::map< int, TC * > _opcode_TC_map
This is the correspondence list between OPCODE and TC object. Here will be fetched and added all the TCs.
ERROR_STATE _error
Detailed Description
the telecommands in a std::map . It is also called by GlobalReceiver upon receiving commanding instruction.
Definition at line 19 of file TCProcessor.h.
Member Enumeration Documentation
enum TCProcessor::ERROR_STATE
defines all the error states the TC Processor can report.
Enumerator:
NO_ERROR
nominal state
INVALID_OPCODE
if attempting to perform an action on an invalid OPCODE
INVALID_ACTION
if attempting to perform an action which is not defined
Definition at line 43 of file TCProcessor.h.
enum TCProcessor::TC_ACTION
Defines different actions available for commands.
Enumerator:
EXECUTE
this executes the given TC
ENABLE
this enables the given TC
DISABLE
this disables the given TC
Definition at line 34 of file TCProcessor.h.
Constructor & Destructor Documentation
TCProcessor::TCProcessor ()
The constructor only initializes private attributes of this class.
Definition at line 10 of file TCProcessor.cpp.
References _error, and NO_ERROR.
TCProcessor::~TCProcessor () virtual
Definition at line 40 of file TCProcessor.cpp.
Member Function Documentation
void TCProcessor::define_ () private
The define_ function will define all the TCs available. It is called from the constructor and it populates the map. This is where the correspondence between the OPCODE and the given TC is done. Note that this also where the Start of Service tool output should be place (for TC generation).
Definition at line 43 of file TCProcessor.cpp.
References _opcode_TC_map.
Referenced by init().
void TCProcessor::init ()
The init function will call 'init' on all the telecommands of this class. This function must be called from the setup function in the main.
Definition at line 14 of file TCProcessor.cpp.
References define_().
Referenced by setup().
void TCProcessor::perform (TC_ACTION action, int opcode)
This function will perform the given action on the given opcode. The internal error variable will reflect whether the OPCODE is valid. Due to the limiting actions exposed by TC_ACTION, there is no need to check for the validity of the action.
Parameters
opcode
action
Definition at line 21 of file TCProcessor.cpp.
References _error, _opcode_TC_map, DISABLE, TC::disable(), ENABLE, TC::enable(), TC::exec(), EXECUTE, and INVALID_OPCODE.
Referenced by loop().
void TCProcessor::processRecv (String payload)
This function processes the input string which contains the OPCODE to concerned along with the action to take. This function will set the internal error variable accordingly, if there is an error of course. This function calls the process function which manages command execution, enabling, disabling, etc.
Parameters
payload input passed on by the GlobalReceiver in order to process the desired command.
Definition at line 18 of file TCProcessor.cpp.
Member Data Documentation
ERROR_STATE TCProcessor::_error private
Definition at line 80 of file TCProcessor.h.
Referenced by perform(), and TCProcessor().
std::map<int, TC*> TCProcessor::_opcode_TC_map private
This is the correspondence list between OPCODE and TC object. Here will be fetched and added all the TCs.
Definition at line 78 of file TCProcessor.h.
Referenced by define_(), and perform().
The documentation for this class was generated from the following files:
TCProcessor.h
TCProcessor.cpp