Embedded Software: Processors::TCProcessor Class Reference
Processors::TCProcessor Class Reference
This class manages all the telecommands in a std::map . It is also called by GlobalReceiver upon receiving commanding instruction.
#include <TCProcessor.h>
Public Types
enum TC_ACTION { EXECUTE, ENABLE, DISABLE }
enum ERROR_STATE { NO_ERROR, INVALID_OPCODE, INVALID_ACTION }
Public Member Functions
TCProcessor ()
The constructor only initializes private attributes of this class.
void init ()
The init function will call 'init' on all the telecommands of this class. This function must be called from the setup function in the main.
void processRecv (String payload)
This function processes the input string which contains the OPCODE to concerned along with the action to take. This function will set the internal error variable accordingly, if there is an error of course. This function calls the process function which manages command execution, enabling, disabling, etc. The payload must be formatted as follows (in chars): xxxy where x is the OPCODE on 3 chars and y is the action on 1 char. The action is one of the following:
void perform (TC_ACTION action, uint8_t opcode)
This function will perform the given action on the given opcode. The internal error variable will reflect whether the OPCODE is valid. Due to the limiting actions exposed by TC_ACTION, there is no need to check for the validity of the action.
virtual ~TCProcessor ()
Private Member Functions
void definitions_ ()
The definitions_ function will define all the TCs available. It is called from the constructor and it populates the map. This is where the correspondence between the OPCODE and the given TC is done. Note that this also where the Start of Service tool output should be place (for TC generation).
Private Attributes
std::map< uint8_t,
TC::AbstractTC * > _opcode_TC_map
This is the correspondence list between OPCODE and TC object. Here will be fetched and added all the TCs.
ERROR_STATE _error
Detailed Description
This class manages all the telecommands in a std::map . It is also called by GlobalReceiver upon receiving commanding instruction.
Definition at line 21 of file TCProcessor.h.
Member Enumeration Documentation
enum Processors::TCProcessor::ERROR_STATE
defines all the error states the TC Processor can report.
Enumerator:
NO_ERROR
nominal state
INVALID_OPCODE
if attempting to perform an action on an invalid OPCODE
INVALID_ACTION
if attempting to perform an action which is not defined
Definition at line 45 of file TCProcessor.h.
enum Processors::TCProcessor::TC_ACTION
Defines different actions available for commands.
Enumerator:
EXECUTE
this executes the given TC
ENABLE
this enables the given TC
DISABLE
this disables the given TC
Definition at line 36 of file TCProcessor.h.
Constructor & Destructor Documentation
Processors::TCProcessor::TCProcessor ()
The constructor only initializes private attributes of this class.
Definition at line 10 of file TCProcessor.cpp.
References _error, and NO_ERROR.
Processors::TCProcessor::~TCProcessor () virtual
Definition at line 65 of file TCProcessor.cpp.
Member Function Documentation
void Processors::TCProcessor::definitions_ () private
The definitions_ function will define all the TCs available. It is called from the constructor and it populates the map. This is where the correspondence between the OPCODE and the given TC is done. Note that this also where the Start of Service tool output should be place (for TC generation).
Definition at line 68 of file TCProcessor.cpp.
References _opcode_TC_map.
Referenced by init().
void Processors::TCProcessor::init ()
The init function will call 'init' on all the telecommands of this class. This function must be called from the setup function in the main.
Definition at line 14 of file TCProcessor.cpp.
References definitions_().
Referenced by setup().
void Processors::TCProcessor::perform (TC_ACTION action, uint8_t opcode)
This function will perform the given action on the given opcode. The internal error variable will reflect whether the OPCODE is valid. Due to the limiting actions exposed by TC_ACTION, there is no need to check for the validity of the action.
Parameters
opcode
action
Definition at line 46 of file TCProcessor.cpp.
References _error, _opcode_TC_map, DISABLE, TC::AbstractTC::disable(), ENABLE, TC::AbstractTC::enable(), TC::AbstractTC::exec(), EXECUTE, and INVALID_OPCODE.
Referenced by main(), and processRecv().
void Processors::TCProcessor::processRecv (String payload)
This function processes the input string which contains the OPCODE to concerned along with the action to take. This function will set the internal error variable accordingly, if there is an error of course. This function calls the process function which manages command execution, enabling, disabling, etc. The payload must be formatted as follows (in chars): xxxy where x is the OPCODE on 3 chars and y is the action on 1 char. The action is one of the following:
1: execute
3: enable
5: disable
For example, to EXECUTE OPCODE 15, this function must receive 0151.
Parameters
payload input passed on by the GlobalReceiver in order to process the desired command.
Definition at line 18 of file TCProcessor.cpp.
References _error, DISABLE, ENABLE, EXECUTE, INVALID_ACTION, INVALID_OPCODE, and perform().
Referenced by Processors::GlobalReceiver::process().
Member Data Documentation
ERROR_STATE Processors::TCProcessor::_error private
Definition at line 89 of file TCProcessor.h.
Referenced by perform(), processRecv(), and TCProcessor().
std::map<uint8_t, TC::AbstractTC*> Processors::TCProcessor::_opcode_TC_map private
This is the correspondence list between OPCODE and TC object. Here will be fetched and added all the TCs.
Note
Due to the definition of this map, there is a maximum of 256 TCs available. Setting this maximum allows faster TC fetching.
Definition at line 87 of file TCProcessor.h.
Referenced by definitions_(), and perform().
The documentation for this class was generated from the following files:
TCProcessor.h
TCProcessor.cpp