Embedded Software: GlobalReceiver Class Reference
GlobalReceiver Class Reference
#include <GlobalReceiver.h>
Public Member Functions
GlobalReceiver ()
void process ()
This function fetches and processes the input. It calls com's recv() to read the latest information.
void setCom (AbstractCommunication &comInstance)
This function sets the communication pointer. This is used when the empty constructor is used.
void setTCProcessor (TCProcessor &tcProcInstance)
This function sets the TC processor. This is used when the empty constructor is used.
virtual ~GlobalReceiver ()
Private Attributes
AbstractCommunication * _com
TCProcessor * _tcProcessor
Detailed Description
Definition at line 14 of file GlobalReceiver.h.
Constructor & Destructor Documentation
GlobalReceiver::GlobalReceiver ()
Definition at line 10 of file GlobalReceiver.cpp.
References _com, and _tcProcessor.
GlobalReceiver::~GlobalReceiver () virtual
Definition at line 59 of file GlobalReceiver.cpp.
Member Function Documentation
void GlobalReceiver::process ()
This function fetches and processes the input. It calls com's recv() to read the latest information.
Communicating to the pod
This character (of the String) is the type of action requested. There are currently only four actions defines, but we use a full character in order to leave space for more actions later, but especially because of ease of testing. Only the first character is read in this function. All the rest are sent to the appropriate AbstractReceiverProcessor.
Defined actions
Command: "1"
This is how ask the pod to execute a given command.
Procedure: "3"
This is how to start an embedded procedure on the pod.
Telemetery information: "5"
This allows to request telemetry information of any given telemetry in the next telemetry frame.
Meta: "7"
This includes commands related to meta around the pod, not its operational commands.
Definition at line 27 of file GlobalReceiver.cpp.
References _com, _tcProcessor, byte_to_binary(), TCProcessor::processRecv(), AbstractCommunication::recv(), and AbstractCommunication::sendf().
Referenced by loop().
void GlobalReceiver::setCom (AbstractCommunication & comInstance)
This function sets the communication pointer. This is used when the empty constructor is used.
Parameters
comInstance communication instance
Definition at line 51 of file GlobalReceiver.cpp.
References _com.
Referenced by setup().
void GlobalReceiver::setTCProcessor (TCProcessor & tcProcInstance)
This function sets the TC processor. This is used when the empty constructor is used.
Parameters
tcProcInstance TCProcessor instance
Definition at line 55 of file GlobalReceiver.cpp.
References _tcProcessor.
Referenced by setup().
Member Data Documentation
AbstractCommunication* GlobalReceiver::_com private
Definition at line 48 of file GlobalReceiver.h.
Referenced by GlobalReceiver(), process(), and setCom().
TCProcessor* GlobalReceiver::_tcProcessor private
Definition at line 49 of file GlobalReceiver.h.
Referenced by GlobalReceiver(), process(), and setTCProcessor().
The documentation for this class was generated from the following files:
GlobalReceiver.h
GlobalReceiver.cpp