Embedded Software: Debug Class Reference
Debug Class Reference
#include <Debug.h>
Public Types
enum DEBUG_LEVEL { INFO = 0, WARN = 5, ERROR = 10 }
Public Member Functions
Debug (AbstractCommunication *com, DEBUG_LEVEL lvl)
Constructor of the Debug class.
Debug ()
Empty constructor for initialization only.
virtual ~Debug ()
void info (String msg)
void warn (String msg)
void error (String msg)
void info (String msg, String location)
This function sends an informational debug message. The location parameter is optional. info(String msg);.
void warn (String msg, String location)
This function sends a warning debug message. The location parameter is optional. warn(String msg);.
void error (String msg, String location)
This function sends an error debug message. The location parameter is optional. error(String msg);.
void setCom (AbstractCommunication *com)
This function sets the communication pointer. This is used when the empty constructor is used.
void setLevel (DEBUG_LEVEL lvl)
Private Attributes
AbstractCommunication * com
DEBUG_LEVEL lvl
Static Private Attributes
static const String DEFAULT_LOCATION = "None"
Detailed Description
Definition at line 13 of file Debug.h.
Member Enumeration Documentation
enum Debug::DEBUG_LEVEL
Enumerator:
INFO
this is the info level
WARN
this is the warning level
ERROR
this is the error level
Definition at line 18 of file Debug.h.
Constructor & Destructor Documentation
Debug::Debug (AbstractCommunication * com, DEBUG_LEVEL lvl)
Constructor of the Debug class.
Parameters
com AbstractCommunication instance used for communication
lvl level of debugging needed
Definition at line 12 of file Debug.cpp.
References com, and lvl.
Debug::Debug ()
Empty constructor for initialization only.
Definition at line 44 of file Debug.cpp.
References com, INFO, and lvl.
Debug::~Debug () virtual
Definition at line 17 of file Debug.cpp.
Member Function Documentation
void Debug::error (String msg)
Definition at line 28 of file Debug.cpp.
References DEFAULT_LOCATION.
void Debug::error (String msg, String location)
This function sends an error debug message. The location parameter is optional. error(String msg);.
Parameters
msg message to be sent
location location where this message was emitted
Definition at line 53 of file Debug.cpp.
References com, ERROR, lvl, and AbstractCommunication::send().
void Debug::info (String msg)
Definition at line 20 of file Debug.cpp.
References DEFAULT_LOCATION.
Referenced by loop(), and setup().
void Debug::info (String msg, String location)
This function sends an informational debug message. The location parameter is optional. info(String msg);.
Parameters
msg message to be sent
location location where this message was emitted
Definition at line 32 of file Debug.cpp.
References com, INFO, lvl, and AbstractCommunication::send().
void Debug::setCom (AbstractCommunication * com)
This function sets the communication pointer. This is used when the empty constructor is used.
Parameters
com communication instance
Definition at line 49 of file Debug.cpp.
References com.
Referenced by setup().
void Debug::setLevel (DEBUG_LEVEL lvl)
Definition at line 59 of file Debug.cpp.
References lvl.
Referenced by setup().
void Debug::warn (String msg)
Definition at line 24 of file Debug.cpp.
References DEFAULT_LOCATION.
Referenced by loop().
void Debug::warn (String msg, String location)
This function sends a warning debug message. The location parameter is optional. warn(String msg);.
Parameters
msg message to be sent
location location where this message was emitted
Definition at line 38 of file Debug.cpp.
References com, lvl, AbstractCommunication::send(), and WARN.
Member Data Documentation
AbstractCommunication* Debug::com private
Definition at line 66 of file Debug.h.
Referenced by Debug(), error(), info(), setCom(), and warn().
const String Debug::DEFAULT_LOCATION = "None" static private
Definition at line 67 of file Debug.h.
Referenced by error(), info(), and warn().
DEBUG_LEVEL Debug::lvl private
Definition at line 68 of file Debug.h.
Referenced by Debug(), error(), info(), setLevel(), and warn().
The documentation for this class was generated from the following files:
Debug.h
Debug.cpp