Embedded Software: Communicators::AbstractCommunication Class Reference
Communicators::AbstractCommunication Class Reference abstract
This class defines how all communication should be done.
#include <AbstractCommunication.h>
Public Types
enum DEBUG_LEVEL { INFO = 0, WARN = 5, ERROR = 10 }
Public Member Functions
AbstractCommunication ()
The constructor should initialize the communication with the control system. This includes everything needed prior to starting to communicate with the control system.
virtual ~AbstractCommunication ()
virtual void init ()=0
This function initializes the communication. It will be called from the setup function.
virtual void send (String payload)=0
This function sends information through the communication pipe.
virtual String recv ()=0
This function reads data from the pipe and returns this as a string.
void sendf (String payload,...)
This function sends a formatted string through the communication pipe.
void info (String msg)
void warn (String msg)
void error (String msg)
void info (String msg, String location)
This function sends an informational debug message. The location parameter is optional. info(String msg);.
void warn (String msg, String location)
This function sends a warning debug message. The location parameter is optional. warn(String msg);.
void error (String msg, String location)
This function sends an error debug message. The location parameter is optional. error(String msg);.
void setLevel (DEBUG_LEVEL lvl)
Private Attributes
DEBUG_LEVEL lvl
Static Private Attributes
static const String DEFAULT_LOCATION = "None"
Detailed Description
This class defines how all communication should be done.
Definition at line 24 of file AbstractCommunication.h.
Member Enumeration Documentation
enum Communicators::AbstractCommunication::DEBUG_LEVEL
Defines different levels of debugging.
Enumerator:
INFO
this is the info level
WARN
this is the warning level
ERROR
this is the error level
Definition at line 51 of file AbstractCommunication.h.
Constructor & Destructor Documentation
Communicators::AbstractCommunication::AbstractCommunication ()
The constructor should initialize the communication with the control system. This includes everything needed prior to starting to communicate with the control system.
Definition at line 14 of file AbstractCommunication.cpp.
References ERROR, and lvl.
Communicators::AbstractCommunication::~AbstractCommunication () virtual
Definition at line 18 of file AbstractCommunication.cpp.
Member Function Documentation
void Communicators::AbstractCommunication::error (String msg)
Definition at line 31 of file AbstractCommunication.cpp.
References DEFAULT_LOCATION.
void Communicators::AbstractCommunication::error (String msg, String location)
This function sends an error debug message. The location parameter is optional. error(String msg);.
Parameters
msg message to be sent
location location where this message was emitted
Definition at line 47 of file AbstractCommunication.cpp.
References ERROR, lvl, and send().
void Communicators::AbstractCommunication::info (String msg)
Definition at line 23 of file AbstractCommunication.cpp.
References DEFAULT_LOCATION.
Referenced by setup().
void Communicators::AbstractCommunication::info (String msg, String location)
This function sends an informational debug message. The location parameter is optional. info(String msg);.
Parameters
msg message to be sent
location location where this message was emitted
Definition at line 35 of file AbstractCommunication.cpp.
References INFO, lvl, and send().
virtual void Communicators::AbstractCommunication::init () pure virtual
This function initializes the communication. It will be called from the setup function.
Implemented in Communicators::SerialCom.
virtual String Communicators::AbstractCommunication::recv () pure virtual
This function reads data from the pipe and returns this as a string.
Returns
a string representing the data received from the pipe.
Implemented in Communicators::SerialCom.
Referenced by Processors::GlobalReceiver::process().
virtual void Communicators::AbstractCommunication::send (String payload) pure virtual
This function sends information through the communication pipe.
Parameters
payload this is string which represents the payload to be delivered.
Implemented in Communicators::SerialCom.
Referenced by error(), info(), sendf(), and warn().
void Communicators::AbstractCommunication::sendf (String payload, ...)
This function sends a formatted string through the communication pipe.
Parameters
payload this is the string to be formatted with the additional arguments. Works just like printf.
Definition at line 53 of file AbstractCommunication.cpp.
References send().
Referenced by Processors::GlobalReceiver::process().
void Communicators::AbstractCommunication::setLevel (DEBUG_LEVEL lvl)
Definition at line 63 of file AbstractCommunication.cpp.
References lvl.
Referenced by setup().
void Communicators::AbstractCommunication::warn (String msg)
Definition at line 27 of file AbstractCommunication.cpp.
References DEFAULT_LOCATION.
void Communicators::AbstractCommunication::warn (String msg, String location)
This function sends a warning debug message. The location parameter is optional. warn(String msg);.
Parameters
msg message to be sent
location location where this message was emitted
Definition at line 41 of file AbstractCommunication.cpp.
References lvl, send(), and WARN.
Member Data Documentation
const String Communicators::AbstractCommunication::DEFAULT_LOCATION = "None" static private
Definition at line 84 of file AbstractCommunication.h.
Referenced by error(), info(), and warn().
DEBUG_LEVEL Communicators::AbstractCommunication::lvl private
Definition at line 85 of file AbstractCommunication.h.
Referenced by AbstractCommunication(), error(), info(), setLevel(), and warn().
The documentation for this class was generated from the following files:
AbstractCommunication.h
AbstractCommunication.cpp