Embedded Software: main.cpp File Reference
main.cpp File Reference
#include <Arduino.h>
#include "config/config.h"
#include "GlobalReceiver.h"
#include "DigitalWriteTC.h"
#include "TCProcessor.h"
#include <pnew.cpp>
#include "SerialCom.h"
Functions
void setup ()
This function is only ran when the sketch is initialized.
void loop ()
loop() loops while Arduino is powered.
int main (void)
where all the subsystems are started.
Variables
int ledPin = 13
SerialCom com
GlobalReceiver glrcv
TCProcessor tcProcessor
DigitalWriteTC led13_ON = DigitalWriteTC(ledPin, HIGH)
DigitalWriteTC led13_OFF = DigitalWriteTC(ledPin, LOW)
Function Documentation
void loop ()
loop() loops while Arduino is powered.
Definition at line 47 of file main.cpp.
References TC::exec(), TCProcessor::EXECUTE, TCProcessor::perform(), and GlobalReceiver::process().
Referenced by main().
int main (void)
where all the subsystems are started.
Returns
Definition at line 60 of file main.cpp.
References loop(), and setup().
void setup ()
This function is only ran when the sketch is initialized.
Definition at line 31 of file main.cpp.
References AbstractCommunication::info(), SerialCom::init(), DigitalWriteTC::init(), TCProcessor::init(), GlobalReceiver::setCom(), AbstractCommunication::setLevel(), and AbstractCommunication::WARN.
Referenced by main().
Variable Documentation
SerialCom com
Definition at line 22 of file main.cpp.
GlobalReceiver glrcv
Definition at line 23 of file main.cpp.
DigitalWriteTC led13_OFF = DigitalWriteTC(ledPin, LOW)
Definition at line 26 of file main.cpp.
DigitalWriteTC led13_ON = DigitalWriteTC(ledPin, HIGH)
Definition at line 25 of file main.cpp.
int ledPin = 13
The following definition is only to avoid the warning when writing to Flash with PROGMEM.
Definition at line 20 of file main.cpp.
TCProcessor tcProcessor
Definition at line 24 of file main.cpp.